/// <reference types="@cloudflare/workers-types" />
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: 7908ab836aff51461aa2aace7d09e48e)
interface __BaseEnv_Env {
	BLOBS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ORIGIN: string;
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	CLERK_JWT_KEY: string;
	CLERK_ISSUER: string;
	CLERK_AUDIENCE: string;
	CLERK_WEBHOOK_SECRET: string;
	ACCESS_JWT_SECRET: string;
	SESSION_WRAP_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./apps/api/src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "CLERK_PUBLISHABLE_KEY" | "CLERK_SECRET_KEY" | "CLERK_JWT_KEY" | "CLERK_ISSUER" | "CLERK_AUDIENCE" | "CLERK_WEBHOOK_SECRET" | "ACCESS_JWT_SECRET" | "SESSION_WRAP_SECRET">> {}
}
