import React from 'react';
import { addMinor, aggregateCardHistory, calculateAllocations, parseAllocationSettings, parsePortfolioSnapshot, parseCardCapture } from '@finance-tools/portfolio-domain';
import { evaluateMonthly, resolveCategory } from '@finance-tools/card-rules';
import type { CardSettings } from '@finance-tools/card-rules';
import type { CardCapture, Money, PortfolioSnapshot } from '@finance-tools/portfolio-domain';
type Capture = CardCapture | PortfolioSnapshot;
const object = (input: unknown): Record<string, unknown> => input && typeof input === 'object' && !Array.isArray(input) ? input as Record<string, unknown> : {};
const validMoney = (input: unknown): input is Money => { const value = object(input); return Number.isSafeInteger(value.minor) && typeof value.currency === 'string' && /^[A-Z]{3}$/.test(value.currency); };
function capture(input: unknown): input is Capture {
  try { if (input && typeof input === 'object' && 'transactions' in input) parseCardCapture(input); else parsePortfolioSnapshot(input); return true; } catch { return false; }
}
const amount = (value: Money | null) => value ? new Intl.NumberFormat('en-SG', { style: 'currency', currency: value.currency }).format(value.minor / 100) : 'Unknown';
export function FinancialViews({ values, settings, bankSettings }: { values: unknown[]; settings: unknown; bankSettings?: unknown }) {
  const config = object(settings), assignments = object(config.assignments), subcaps = object(config.subcaps);
  const category = (id: string) => typeof assignments[id] === 'string' ? assignments[id] as string : 'Uncategorized';
  const latest = new Map<string, Capture>();
  for (const value of values) if (capture(value) && 'holdings' in value) { const key = `${value.provenance.provider}:${value.accountId}`; const previous = latest.get(key); if (!previous || previous.provenance.capturedAt < value.provenance.capturedAt) latest.set(key, value); }
  return <><AllocationViews snapshots={[...latest.values()].filter((value): value is PortfolioSnapshot => 'holdings' in value)} settings={config.allocations} />{[...latest.values()].map(snapshot => {
    const totals = new Map<string, Money>(), unsafe = new Set<string>();
    const aggregate = (label: string, money: Money) => { const key = `${label} / ${money.currency}`; if (unsafe.has(key)) return; const previous = totals.get(key); try { totals.set(key, { ...money, minor: addMinor(previous?.minor ?? 0, money.minor) }); } catch { totals.delete(key); unsafe.add(key); } };
    if ('holdings' in snapshot) for (const row of snapshot.holdings) { if (row.valuation) aggregate(`${category(row.id)} / ${row.section}`, row.valuation); }
    else for (const row of snapshot.transactions) aggregate(`${row.postingDate.slice(0, 7)} / ${category(row.id)}`, row.spending);
    return <article key={snapshot.id}><h3>{snapshot.provenance.provider}</h3><p>Captured {snapshot.provenance.capturedAt} · source: {snapshot.provenance.source}</p><p className="warning">Incomplete snapshot{Date.now() - Date.parse(snapshot.provenance.capturedAt) > 86400000 ? ' · Stale (>24h)' : ''}{snapshot.provenance.flags.length ? ` · ${snapshot.provenance.flags.join(', ')}` : ''}</p>
      {!!unsafe.size && <p role="alert">Some totals exceed safe integer precision and are unavailable.</p>}<div className="grid">{[...totals].map(([label, total]) => <div className="metric" key={label}><small>{label}</small><strong>{amount(total)}</strong>{!('holdings' in snapshot) && (() => { const categoryName = label.split(' / ').slice(1, -1).join(' / '), cap = object(subcaps[categoryName]); return validMoney(cap) && cap.minor >= 0 && cap.currency === total.currency ? <p>Configured cap {amount(cap)} · remaining {Number.isSafeInteger(cap.minor - total.minor) ? amount({ ...total, minor: Math.max(0, cap.minor - total.minor) }) : 'Unknown'}</p> : <p>No configured subcap. Classification is user-assigned, not a bank eligibility decision.</p>; })()}</div>)}</div>
      <div className="table-scroll"><table><thead><tr>{('holdings' in snapshot ? ['Holding', 'Category', 'Valuation', 'Cost basis', 'Profit', 'Return', 'Warnings / ID'] : ['Posted', 'Merchant', 'Category', 'Spending', 'ID']).map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{'holdings' in snapshot ? snapshot.holdings.map(row => <tr key={row.id}><td>{row.name || row.code}</td><td>{category(row.id)}</td><td>{amount(row.valuation)}</td><td>{validMoney(row.costBasis) ? amount(row.costBasis) : 'Unknown'}</td><td>{validMoney(row.profit) ? amount(row.profit) : 'Unknown'}</td><td>{typeof row.returnPercent === 'number' ? `${row.returnPercent}%` : 'Unknown'}</td><td>{row.flags.join(', ')}<details><summary>Assignment ID</summary>{row.id}</details></td></tr>) : snapshot.transactions.map(row => <tr key={row.id}><td>{row.postingDate}</td><td>{row.merchant}</td><td>{category(row.id)}</td><td>{amount(row.spending)}</td><td><details><summary>Assignment ID</summary>{row.id}</details></td></tr>)}</tbody></table></div></article>;
  })}{!latest.size && <p>No portfolio holdings loaded.</p>}<BankHistory values={values} settings={bankSettings} /></>;
}
function AllocationViews({ snapshots, settings }: { snapshots: PortfolioSnapshot[]; settings: unknown }) {
  let results: ReturnType<typeof calculateAllocations>;
  try { results = calculateAllocations(snapshots, parseAllocationSettings(settings ?? { scopes: [] })); } catch { return <p role="alert">Invalid allocation settings or source data. No target/drift calculation is shown.</p>; }
  return <>{results.map(result => <article key={result.scope.id}><h3>{result.scope.bucket} · target versus actual</h3><p>Account {result.scope.accountId} · {result.scope.accountType} · {result.scope.section} · {result.scope.currency}{result.scope.goalId ? ` · goal ${result.scope.goalId}` : ''}</p><p>Actual {(result.actualTotalMinor / 100).toFixed(2)} · projected {(result.projectedTotalMinor / 100).toFixed(2)}</p><p className="warning">Incomplete balance comparison, not a time-weighted return or recommendation. {result.warnings.join(', ')}</p><div className="table-scroll"><table><thead><tr>{['Holding ID', 'Actual', 'Actual %', 'Target', 'Target %', 'Drift bps', 'Target − actual', 'Fixed / excluded'].map(text => <th key={text}>{text}</th>)}</tr></thead><tbody>{result.rows.map(row => <tr key={row.holdingId}><td>{row.holdingId}</td><td>{row.actualMinor === null ? 'Unknown' : (row.actualMinor / 100).toFixed(2)}</td><td>{row.actualBps === null ? 'Unknown' : (row.actualBps / 100).toFixed(2)}</td><td>{row.targetMinor === null ? 'Unknown' : (row.targetMinor / 100).toFixed(2)}</td><td>{row.targetBps === null ? 'Unknown' : (row.targetBps / 100).toFixed(2)}</td><td>{row.driftBps ?? 'Unknown'}</td><td>{row.deltaMinor === null ? 'Unknown' : (row.deltaMinor / 100).toFixed(2)}</td><td>{row.fixed ? 'Fixed' : ''} {row.excluded ? 'Excluded' : ''} {row.warnings.join(', ')}</td></tr>)}</tbody></table></div></article>)}</>;
}
function BankHistory({ values, settings }: { values: unknown[]; settings: unknown }) {
  const cards = values.filter((value): value is CardCapture => capture(value) && 'transactions' in value && value.persistence === 'account-bound' && !value.provenance.flags.includes('ACCOUNT_CONTEXT_UNAVAILABLE') && !value.provenance.flags.includes('EPHEMERAL_ONLY'));
  let histories: ReturnType<typeof aggregateCardHistory>;
  try { histories = aggregateCardHistory(cards, new Date().toISOString()); } catch { return <p role="alert">Bank history has invalid records. No potentially inaccurate aggregate is displayed.</p>; }
  const config = object(object(settings).cards);
  return <>{histories.map(history => {
    const cardConfig = (config[history.accountId] ?? { selectedCategories: [] }) as CardSettings;
    const validSettings = !!cardConfig && Array.isArray(cardConfig.selectedCategories) && cardConfig.selectedCategories.every(x => typeof x === 'string') && (cardConfig.defaultCategory === undefined || typeof cardConfig.defaultCategory === 'string') && (cardConfig.merchantMap === undefined || (!!cardConfig.merchantMap && typeof cardConfig.merchantMap === 'object' && !Array.isArray(cardConfig.merchantMap) && Object.values(cardConfig.merchantMap).every(x => typeof x === 'string')));
    let results: ReturnType<typeof evaluateMonthly> = [];
    try { if (!validSettings) throw new Error(); results = evaluateMonthly(history.card, history.transactions, cardConfig, new Date().toISOString(), { ambiguousMonths: history.ambiguousMonths, coverage: history.coverage }); } catch { /* Invalid or non-SGD rule input fails closed. */ }
    return <article key={`${history.card}:${history.accountId}`}><h3>{history.card} · account history</h3><p>{history.captureIds.length} retained captures, deduplicated by account and stable transaction ID. Latest capture: {history.provenance.capturedAt}</p><p className="warning">Coverage unknown / incomplete. {history.changes.length} transaction corrections. {history.provenance.flags.join(', ')}</p>{Date.now() - Date.parse(history.provenance.capturedAt) > 86400000 && <p className="warning">Stale capture (&gt;24 hours).</p>}
      {!results.length && <p>Rule calculation unavailable or no retained SGD activity. Configure cards[accountId].selectedCategories / merchantMap in bank-subcaps settings. Account ID: {history.accountId}</p>}
      {results.map(result => <section key={result.month}><h4>{result.month}</h4>{history.totalsConfidence === 'latest-capture-lower-bound' || history.ambiguousMonths.includes(result.month) || result.remainingMinor === null ? <p className="warning">Observed window only: SGD {(result.totalMinor / 100).toFixed(2)} (lower bound / incomplete). Ambiguous identity or partial retention month: eligible and exact remaining amounts are unknown. {result.warnings.join(', ')}</p> : <><p>Total SGD {(result.totalMinor / 100).toFixed(2)} · reference eligible SGD {(result.eligibleMinor / 100).toFixed(2)}</p>{Object.entries(result.remainingMinor ?? {}).map(([category, minor]) => <p key={category}>{category}: remaining SGD {(minor / 100).toFixed(2)}</p>)}</>}<p>Reference cap SGD {(result.rule.capMinor / 100).toFixed(2)} ({result.rule.mode})</p><p className="warning">{result.rule.status}: {result.rule.version} · {result.rule.source}. Effective date unknown. Verify current issuer eligibility; these reference rules are not authoritative.</p></section>)}
      <div className="table-scroll"><table><thead><tr><th>Posted</th><th>Merchant</th><th>Rule category</th><th>Spending</th></tr></thead><tbody>{history.transactions.map(row => <tr key={row.id}><td>{row.postingDate}</td><td>{row.merchant}</td><td>{validSettings ? resolveCategory(row.merchant, cardConfig, history.card) : 'Invalid settings'}</td><td>{amount(row.spending)}</td></tr>)}</tbody></table></div>
      {!!history.changes.length && <details><summary>Corrections & provenance</summary>{history.changes.map((change, index) => <p key={index}>{change.capturedAt}: {change.transactionId} · {amount(change.previous.spending)} → {amount(change.replacement.spending)} · {change.replacement.merchant}</p>)}</details>}
    </article>;
  })}{!histories.length && <p>No explicitly account-bound card history loaded. Unidentified bank captures stay ephemeral in the script until binding.</p>}</>;
}
